import { useState } from 'react';
const questions=[{q:'If X ~ N(100, 15²), what is the Z-score for X = 130?',options:['1.5','2.0','0.5','3.0'],correct:1,exp:'Z = (130 - 100) / 15 = 30 / 15 = 2.0'},{q:'In a standard normal distribution, what percentage of data falls between Z = -1.96 and Z = +1.96?',options:['68%','90%','95%','99.7%'],correct:2,exp:'The interval ±1.96σ captures approximately 95% of the data.'},{q:'If the mean is 50 and std dev is 10, what is P(X < 50)?',options:['0.25','0.50','0.68','1.00'],correct:1,exp:'Due to symmetry, exactly half lies below the mean. P(X < μ) = 0.50.'},{q:'Which change will make the normal curve taller and narrower?',options:['Increasing μ','Decreasing σ','Increasing σ','Decreasing μ'],correct:1,exp:'A smaller σ concentrates data closer to the mean.'},{q:'The total area under the normal distribution curve equals:',options:['0','0.5','1.0','It depends on σ'],correct:2,exp:'Total area under any PDF equals 1.'},{q:'For N(200, 25²), find P(X > 250).',options:['0.0228','0.1587','0.9772','0.0013'],correct:0,exp:'Z = (250-200)/25 = 2.0. P(Z>2) = 1 - 0.9772 = 0.0228.'},{q:'In the empirical rule, what % falls within ±3σ?',options:['68.27%','95.45%','99.73%','100%'],correct:2,exp:'The three-sigma rule: 99.73% within ±3σ.'},{q:'A Z-score of -1.5 means the value is:',options:['1.5 std devs above the mean','1.5 std devs below the mean','1.5 units below zero','In the top 15%'],correct:1,exp:'Negative Z = below the mean by 1.5 standard deviations.'},{q:'The Central Limit Theorem states that:',options:['All populations are normal','Sample means approach normal as n increases','Larger samples have smaller means','Mean always equals median'],correct:1,exp:'CLT: distribution of sample means → normal as n increases.'},{q:'For a Six Sigma process, the defect rate is:',options:['6 per hundred','3.4 per million opportunities','6 per thousand','0.1 per million'],correct:1,exp:'Six Sigma = 3.4 DPMO.'}];

export default function QuizSection(){
  const [answers,setAnswers]=useState({});const [showResults,setShowResults]=useState(false);
  const handleAnswer=(qi,oi)=>{if(showResults)return;setAnswers({...answers,[qi]:oi});};
  const score=Object.entries(answers).filter(([qi,oi])=>questions[parseInt(qi)].correct===oi).length;
  const allDone=Object.keys(answers).length===questions.length;
  return(
    <section id="quiz" className="py-24 px-6 lg:pl-24 bg-white"><div className="max-w-4xl mx-auto">
      <div className="mb-12"><span className="text-accent font-mono text-sm tracking-wider">CHAPTER 06</span><h2 className="font-display text-4xl sm:text-5xl font-bold mt-2 mb-6">Test Your <span className="text-accent italic">Knowledge</span></h2><p className="text-lg text-slate max-w-2xl">10 questions. Select your answer, then submit.</p><div className="w-20 h-1 bg-gold rounded-full mt-6"/></div>
      <div className="space-y-6">{questions.map((q,qi)=>{const ans=answers[qi]!==undefined;const ok=showResults&&answers[qi]===q.correct;const wrong=showResults&&ans&&answers[qi]!==q.correct;return(
        <div key={qi} className={`rounded-2xl border p-6 transition-all ${showResults?(ok?'border-sage/30 bg-sage/5':wrong?'border-accent/30 bg-accent/5':'border-gold/10 bg-white'):(ans?'border-ink/20 bg-white':'border-gold/10 bg-white')}`}>
          <div className="flex items-start gap-3 mb-4"><span className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-ink text-white font-mono text-sm font-bold flex-shrink-0">{qi+1}</span><p className="font-medium text-ink text-lg leading-snug">{q.q}</p></div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 ml-11">{q.options.map((opt,oi)=>{const sel=answers[qi]===oi;const corr=showResults&&oi===q.correct;return(<button key={oi} onClick={()=>handleAnswer(qi,oi)} className={`quiz-option text-left px-4 py-3 rounded-xl border text-sm font-medium transition-all ${showResults?(corr?'quiz-correct border-sage text-sage':sel&&!corr?'quiz-wrong border-accent text-accent':'border-gold/10 text-slate/50'):(sel?'border-ink bg-ink/5 text-ink':'border-gold/20 text-slate hover:border-ink/30')}`}><span className="font-mono mr-2">{String.fromCharCode(65+oi)}.</span>{opt}{showResults&&corr&&' ✓'}{showResults&&sel&&!corr&&' ✗'}</button>);})}</div>
          {showResults&&(ok||wrong)&&<div className={`mt-3 ml-11 p-3 rounded-lg text-sm ${ok?'bg-sage/10 text-sage':'bg-accent/10 text-accent'}`}>{q.exp}</div>}
        </div>);})}</div>
      <div className="mt-8 flex flex-col sm:flex-row items-center gap-4">
        {!showResults?<button onClick={()=>setShowResults(true)} disabled={!allDone} className={`px-8 py-4 rounded-2xl font-semibold text-lg transition-all ${allDone?'bg-accent text-white shadow-lg shadow-accent/20 hover:shadow-xl hover:-translate-y-0.5':'bg-slate/20 text-slate/50 cursor-not-allowed'}`}>Submit Answers ({Object.keys(answers).length}/{questions.length})</button>
        :<><div className="bg-ink rounded-2xl px-8 py-4 text-center"><div className="text-sm text-white/50">Your Score</div><div className="text-4xl font-display font-bold text-gold">{score}/{questions.length}</div><div className="text-sm text-white/50">{score>=8?'Excellent!':score>=6?'Good effort!':'Keep practising!'}</div></div><button onClick={()=>{setAnswers({});setShowResults(false);}} className="px-6 py-3 bg-accent/10 text-accent rounded-xl font-semibold hover:bg-accent/20">Retry Quiz</button></>}
      </div>
    </div></section>);
}
